//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/onePlatformTwoCommon/dependencies.txt`
//

expect fun c1_platformDependentC1(): String
fun c1_platformIndependentC1() = "common"

fun TestC1() {
  c1_platformIndependentC1()
  c1_platformDependentC1()
}
