//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/simpleJsJvmProjectWithTests/dependencies.txt`
//

expect fun cTests_platformDependentCTests(): String
fun cTests_platformIndependentCTests() = "common"
