//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/simpleJsJvmProjectWithTests/dependencies.txt`
//

public class PJvmMainJavaClass {
    public String doStuff() {
       return "pJvmMain";
    }
}