//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/simpleJsJvmProjectWithTests/dependencies.txt`
//

actual fun cMain_platformDependentCMain(): String = "pJvmMain"
fun pJvmMain_platformOnly() = "pJvmMain"

fun pJvmMainTest() {
  pJvmMain_platformOnly()
  PJvmMainJavaClass().doStuff()
  cMain_platformIndependentCMain()
  cMain_platformDependentCMain()
}
