//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/simpleJsJvmProjectWithTests/dependencies.txt`
//

actual fun cTests_platformDependentCTests(): String = "pJvmTests"
fun pJvmTests_platformOnly() = "pJvmTests"

fun pJvmTestsTest() {
  cTests_platformIndependentCTests()
  cTests_platformDependentCTests()
  pJvmTests_platformOnly()
  JavaClass().doStuff()
}
