//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/simpleJsJvmProjectWithTests/dependencies.txt`
//

actual fun cTests_platformDependentCTests(): String = "pJvmTests"
fun pJvmTests_platformOnly() = "pJvmTests"

fun pJvmTestsTest() {
  pJvmTests_platformOnly()
  PJvmTestsJavaClass().doStuff()
  pJvmMain_platformOnly()
  PJvmMainJavaClass().doStuff()
  cMain_platformIndependentCMain()
  cMain_platformDependentCMain()
  cTests_platformIndependentCTests()
  cTests_platformDependentCTests()
}
