//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/onePlatformTwoCommon/dependencies.txt`
//

actual fun c1_platformDependentC1(): String = "pJs"
actual fun c2_platformDependentC2(): String = "pJs"
fun pJs_platformOnly() = "pJs"

fun TestPJs() {
  pJs_platformOnly()
  c1_platformIndependentC1()
  c1_platformDependentC1()
  c2_platformIndependentC2()
  c2_platformDependentC2()
}
