//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/regularDependensOnMultiplatform/dependencies.txt`
//

fun rJs_platformOnly() = "rJs"

fun rJsTest() {
  rJs_platformOnly()
  pJs_platformOnly()
  c_platformIndependentC()
  c_platformDependentC()
}
