//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/regularDependensOnMultiplatform/dependencies.txt`
//

fun rJvm_platformOnly() = "rJvm"

fun rJvmTest() {
  rJvm_platformOnly()
  RJvmJavaClass().doStuff()
  pJvm_platformOnly()
  PJvmJavaClass().doStuff()
  c_platformIndependentC()
  c_platformDependentC()
}
