//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

actual fun bc_platformDependentBc(): String = "bJs"
fun bJs_platformOnly() = "bJs"

fun bJsTest() {
  bc_platformIndependentBc()
  bc_platformDependentBc()
  bJs_platformOnly()
}
