//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

actual fun bc_platformDependentBc(): String = "bJvm"
fun bJvm_platformOnly() = "bJvm"

fun bJvmTest() {
  bJvm_platformOnly()
  BJvmJavaClass().doStuff()
  bc_platformIndependentBc()
  bc_platformDependentBc()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  aJvm_platformOnly()
  AJvmJavaClass().doStuff()
}
