//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

actual fun bc_platformDependentBc(): String = "bJvm"
fun bJvm_platformOnly() = "bJvm"

fun bJvmTest() {
  bc_platformIndependentBc()
  bc_platformDependentBc()
  bJvm_platformOnly()
  JavaClass().doStuff()
}
