//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/multiplatformDependsOnRegular/dependencies.txt`
//

fun r_platformOnly() = "r"

fun rTest() {
  r_platformOnly()
  RJavaClass().doStuff()
}
