//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/onePlatformTwoCommon/dependencies.txt`
//

public class PJvmJavaClass {
    public String doStuff() {
       return "pJvm";
    }
}