//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

actual fun ac_platformDependentAc(): String = "aJs"
fun aJs_platformOnly() = "aJs"

fun TestAJs() {
  aJs_platformOnly()
  ac_platformIndependentAc()
  ac_platformDependentAc()
}
