//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/simple/dependencies.txt`
//

actual fun c_platformDependentC(): String = "pJs"
fun pJs_platformOnly() = "pJs"

fun pJsTest() {
  pJs_platformOnly()
  c_platformIndependentC()
  c_platformDependentC()
}
