//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/onePlatformTwoCommon/dependencies.txt`
//

expect fun c2_platformDependentC2(): String
fun c2_platformIndependentC2() = "common"
