//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/multiplatformDependsOnRegular/dependencies.txt`
//

expect fun c_platformDependentC(): String
fun c_platformIndependentC() = "common"

fun TestC() {
  c_platformIndependentC()
  c_platformDependentC()
}
