//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

expect fun ac_platformDependentAc(): String
fun ac_platformIndependentAc() = "common"

fun TestAc() {
  ac_platformIndependentAc()
  ac_platformDependentAc()
}
