//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

expect fun bc_platformDependentBc(): String
fun bc_platformIndependentBc() = "common"

fun TestBc() {
  bc_platformIndependentBc()
  bc_platformDependentBc()
  ac_platformIndependentAc()
  ac_platformDependentAc()
}
